version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    command: sh -c "pytest && uvicorn app.main:app --reload --host ${HOST} --port ${WEB_PORT}"
    ports:
      - "8000:8000"
    volumes:
      - .:/task
